### ISSUE TITLE
Changing repeat interval

### ISSUE THREAD

**Issue by hypexr** [bfattori/timersjs#1]
I would like to use this timer with a dynamic repeat interval.

I've tried changing the variable that I've used to specify the timer interval:

``` js
refreshJob = TimersJS.repeater(refreshInterval, function() {
...
```

And I've tried changing the refresh interval variable, killing the timer, and restarting it.  Is this something that should work right now?  If not would it be hard to add?

**Comment by bfattori** [comment]
`refreshInterval` is set once when the timer is created. I'm guessing you want to change it each time that the timer executes? You can modify the interval of a timer by calling its `interval()` method to change the interval. So, you could modify the interval after each execution:

``` javascript
var refreshJob = TimerJS.repeater(refreshInterval, function() {
   ...
   refreshJob.interval(250 + Math.round(Math.random() * 250));
});
```

**Comment by bfattori** [comment]
Old issue.
