### ISSUE TITLE
This library does not work

### ISSUE THREAD

**Issue by mitmelon** [bfattori/timersjs#4]
This error was gotten when using it directly without node 

"Cannot set property 'TimersJS' of undefined"

**Comment by bfattori** [comment]
I believe that if you run this in Strict mode, it will not pass "window" as the default argument if no argument is passed to the closure function. You can explicitly pass window as the closure's argument.

you would only need to change the last line to be }(window};

**Comment by bfattori** [comment]
If you need a fix to the library itself, I will consider changing it.
